# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    env: 
      CURRENT_PACKAGE_VERSION: $(node -e "console.log(require('./package.json').version)")
      MAJOR_MINOR_PACKAGE_VERSION: $(echo $CURRENT_PACKAGE_VERSION | sed -E "s/^([0-9]+\.[0-9]+)\.[0-9]+/\1/g")
      NEW_PACKAGE_VERSION: "$MAJOR_MINOR_PACKAGE_VERSION.$GITHUB_RUN_NUMBER"
      PUBLISH_TAG: latest
    concurrency:
      group: react-components-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm ci
        name: Install packages
      - run: npm run build --if-present
        name: Build
      - run: npm test
        name: Test
      - run: npm run build-storybook
        name: Build storybook
      - name: Publish
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          npm version $NEW_PACKAGE_VERSION -ws
          npm publish --dist-tag $PUBLISH_TAG -ws
